name: OXII NOVA JURNEY
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0439358b-29ce-40c1-8611-ff60823860bc.png
layout_spectrum: 0.6619885170366615
typography_spectrum: 0.8094905754551291
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.08415377628989518
  lightness: 0.48727336153388023
  saturation: 0.30132285645231605
  rhythmicContrast: 0.8490578439086676
title: ''
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: false
coverPrefs:
  filter: false
